In [1]:
import pandas as pd
import numpy as np

In [5]:
num_data = pd.read_csv("newly_confirmed_cases_daily.csv")

In [6]:
print(type(num_data))

<class 'pandas.core.frame.DataFrame'>


In [7]:
num_data.head()

Date  ALL  Hokkaido  Aomori  Iwate  Miyagi  Akita  Yamagata  \
0  2020/1/16    1         0       0      0       0      0         0   
1  2020/1/17    0         0       0      0       0      0         0   
2  2020/1/18    0         0       0      0       0      0         0   
3  2020/1/19    0         0       0      0       0      0         0   
4  2020/1/20    0         0       0      0       0      0         0   

   Fukushima  Ibaraki  ...  Ehime  Kochi  Fukuoka  Saga  Nagasaki  Kumamoto  \
0          0        0  ...      0      0        0     0         0         0   
1          0        0  ...      0      0        0     0         0         0   
2          0        0  ...      0      0        0     0         0         0   
3          0        0  ...      0      0        0     0         0         0   
4          0        0  ...      0      0        0     0         0         0   

   Oita  Miyazaki  Kagoshima  Okinawa  
0     0         0          0        0  
1     0         0          0        0  
2     0         0          0        0  
3     0         0          0        0  
4     0         0          0        0  

[5 rows x 49 columns]

In [10]:
num_data.iloc[0, 26]

0

In [14]:
num_data.iloc[0:1, 0:24] 

Date  ALL  Hokkaido  Aomori  Iwate  Miyagi  Akita  Yamagata  \
0  2020/1/16    1         0       0      0       0      0         0   

   Fukushima  Ibaraki  ...  Tokyo  Kanagawa  Niigata  Toyama  Ishikawa  Fukui  \
0          0        0  ...      0         1        0       0         0      0   

   Yamanashi  Nagano  Gifu  Shizuoka  
0          0       0     0         0  

[1 rows x 24 columns]

In [19]:
num_data.loc[0:4, "Kanagawa"]

0    1
1    0
2    0
3    0
4    0
Name: Kanagawa, dtype: int64

In [24]:
num_data.query("ALL == 2")

Date  ALL  Hokkaido  Aomori  Iwate  Miyagi  Akita  Yamagata  \
20   2020/2/5    2         0       0      0       0      0         0   
26  2020/2/11    2         0       0      0       0      0         0   

    Fukushima  Ibaraki  ...  Ehime  Kochi  Fukuoka  Saga  Nagasaki  Kumamoto  \
20          0        0  ...      0      0        0     0         0         0   
26          0        0  ...      0      0        0     0         0         0   

    Oita  Miyazaki  Kagoshima  Okinawa  
20     0         0          0        0  
26     0         0          0        0  

[2 rows x 49 columns]

In [26]:
nd_num_data = num_data.values
print(type(nd_num_data))
print(nd_num_data)

<class 'numpy.ndarray'>
[['2020/1/16' 1 0 ... 0 0 0]
 ['2020/1/17' 0 0 ... 0 0 0]
 ['2020/1/18' 0 0 ... 0 0 0]
 ...
 ['2023/5/6' 6257 446 ... 38 29 125]
 ['2023/5/7' 14344 658 ... 95 168 254]
 ['2023/5/8' 9489 577 ... 47 86 150]]


In [29]:
c = np.delete(nd_num_data, 0, 1)
print(c)

[[1 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [6257 446 61 ... 38 29 125]
 [14344 658 127 ... 95 168 254]
 [9489 577 87 ... 47 86 150]]


In [34]:
d = nd_num_data[:,1]
d

array([1, 0, 0, ..., 6257, 14344, 9489], dtype=object)

In [38]:
e = nd_num_data[64,:]
print(e)

['2020/3/20' 49 1 0 0 0 0 0 0 0 1 0 3 5 11 2 1 0 1 0 0 0 0 0 5 0 0 1 4 8 0
 0 0 0 0 1 0 0 0 0 0 0 0 0 0 5 0 0 0]


In [44]:
f = np.insert(nd_num_data,0 , e, 0)
print(f)

[['2020/3/20' 49 1 ... 0 0 0]
 ['2020/1/16' 1 0 ... 0 0 0]
 ['2020/1/17' 0 0 ... 0 0 0]
 ...
 ['2023/5/6' 6257 446 ... 38 29 125]
 ['2023/5/7' 14344 658 ... 95 168 254]
 ['2023/5/8' 9489 577 ... 47 86 150]]
